### ISSUE TITLE
Publisher policy should not be displayed when full text is available

### ISSUE THREAD

**Issue by a3nm** [wetneb/dissemin#102]
When full text is available, there's no point in showing the publisher's policy. This could be an embarrassment to some, and clutters the display.

A more useful distinction to make would be to distinguish papers available from a stable repository, vs those available from a webpage (and offer to deposit the latter to Zenodo even though they can also be downloaded)

The simplest would probably be to only have the following icons:

- open-access (full-text available from the publisher)
- full text available from a repository
- full text available from some non-stable source
- full text not available, but it could legally be
- full text not available, publisher policy unclear
- full text not available, but it cannot legally be

Also, search options should probably allow exactly these categories.

**Comment by wetneb** [comment]
I still find it useful to see the unlocked lock on available papers because it makes the look different from preprints (where no publisher policy is available), but that's a side effect that we can achieve in a different way.

The change you suggest is quite big, that would be the occasion to re-think the icons thoroughly (Evarin, are you with us?) By the way, we now try to guess the type of the document (preprint, journal article, proceedings article, book chapter, book, and so on), and this could maybe be reflected by the icons.

**Comment by wetneb** [comment]
This is solved, yay!
