### ISSUE TITLE
Travis build fails because of SSL errors

### ISSUE THREAD

**Issue by wetneb** [wetneb/dissemin#141]
<pre>/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning:
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

  InsecurePlatformWarning</pre>

**Comment by RaitoBezarius** [comment]
I don't know if it is still open (because I see a commit which could have fixed it 0ad904c).

But in either case, it could be solved by installing `requests[security]` if we're using `requests` in the codebase.

(For further reference, it [could help](http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent).)

**Comment by wetneb** [comment]
Thanks! I think the test which was causing this is now disabled on Travis to prevent it from submitting papers to third-party repos on every push.
We're indeed using `requests` but it's currently installed via apt-get on Travis (so I'm not sure how to install it with `[security]` in the same way), feel free to change (moving it to pip dependencies, `requirements_frontend_light.txt`).
