### ISSUE TITLE
Remove empty researcher profiles regularly

### ISSUE THREAD

**Issue by wetneb** [wetneb/dissemin#184]
say, daily

**Comment by RaitoBezarius** [comment]
@wetneb Could you describe more exactly the issue?
Why is there empty researcher profiles?
If there is, why should we remove them?

**Comment by wetneb** [comment]
When a user looks up a researcher, we create a "Researcher" with that name (or use an existing researcher if it has been looked up before), and fetch its papers. Sometimes we don't find any paper for that researcher. In this case, it is not very wise to keep this profile (as we're currently doing), because other users will be proposed to view this empty profile when they look up the researcher.

So, I guess one easy way to solve the issue would be to write a celery task (in backend/tasks.py) that deletes all researchers with empty profiles, when they are not associated to any ORCID, and not affiliated to any institution.

**Comment by RaitoBezarius** [comment]
What happens if a user looks up again a researcher which was previously removed, does the system still search for its papers or does it just consider that he does not have any paper because he was deleted or something like that.

A Celery background task sounds enough, but why not just remove the profile when you finish the scraping task and found out that there were no results with this profile, which triggers the removal process. (I am yet aware with the infrastructure, sorry if I say something off)

**Comment by wetneb** [comment]
Yes, if we look it up again, the system will search again for papers.

About removing the profile earlier: the thing is, we still need to have the profile as long as the user is on the page (otherwise they will get a 404 if they refresh or do anything related to this empty profile)… To get an idea of what actually happens, you can go to http://beta.dissem.in/ and search for an improbable name: you'll be redirected to something like "http://beta.dissem.in/researcher/1234567/" : the number is the pk of the Researcher object in the db. (By the way all these URLs are ugly, but that's another issue…)
